steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/game-ex-be:$COMMIT_SHA", "."]
    id: "build"
  
  # Push Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/game-ex-be:$COMMIT_SHA"]
    id: "push"

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "game-ex-be",  # Consistent naming with image
        "--image",
        "gcr.io/$PROJECT_ID/game-ex-be:$COMMIT_SHA",
        "--update-secrets","KEY_CREDENTIALS=cred-KEY_CREDENTIALS:latest",
        "--platform", "managed",
        "--region", "us-central1",
        "--port", "5000",
        "--timeout", "1000s",
        "--allow-unauthenticated"

      ]
    id: "deploy"

  # Optional: Clean up old images
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "container",
      "images",
      "list-tags",
      "gcr.io/$PROJECT_ID/game-ex-be",
      "--filter=tags~^$COMMIT_SHA",
      "--format=json"
    ]
    id: "cleanup"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"  # Faster builds for Node.js projects
 

